openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - url: http://127.0.0.1:8080/
info:
  description: Flash Card API
  version: "1.0.0"
  title: Flash Card API
  contact:
    email: duttajyotisubhra@gmail.com
tags:
  - name: developers
    description: Secured Admin-only calls
  - name: users
    description: Operations available to regular users
paths:
  /api/deck:
    get:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
    post:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                deck_name:
                  type: string
        description: order placed for purchasing the pet
        required: true



  /api/deck/{deck_name}:
    parameters:
      - in: path
        name: deck_name
        description: pass the deck name
        required: true
        schema:
          type: string
    get:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found

    delete:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can delete
        a deck in the system
        
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
    post:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can delete
        a deck in the system
        
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                card_word:
                  type: string
                card_ans:
                  type: string
        description: order placed for purchasing the pet
        required: true


  /api/deck/{deck_name}/card/{card_no}:
    parameters:
      - in: path
        name: deck_name
        description: pass the deck name
        required: true
        schema:
          type: string
      - in: path
        name: card_no
        description: pass the card number
        required: true
        schema:
          type: integer
  
    get:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can delete
        a deck in the system
        
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
    delete:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can delete
        a deck in the system
        
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
    put:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can delete
        a deck in the system
        
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                card_word:
                  type: string
                card_ans:
                  type: string
        description: order placed for purchasing the pet
        required: true
  /api/user:
    get:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can delete
        a deck in the system
        
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
    post:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can delete
        a deck in the system
        
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                user_id:
                  type: string
                password:
                  type: string
        description: order placed for purchasing the pet
        required: true
  /api/user/{user_id}:
    parameters:
      - in: path
        name: user_id
        description: pass the user ID
        required: true
        schema:
          type: string
  
    get:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can delete
        a deck in the system
        
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
    
    delete:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can delete
        a deck in the system
        
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
    
    put:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can delete
        a deck in the system
        
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                password:
                  type: string
        description: order placed for purchasing the pet
        required: false
    post:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can delete
        a deck in the system
        
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                deck_no:
                  type: string
                last_reviewed:
                  type: string
        description: order placed for purchasing the pet
        required: true
      
  /api/user/{user_id}/deck/{deck_name}:
    parameters:
      - in: path
        name: user_id
        description: pass the user ID
        required: true
        schema:
          type: string
      - in: path
        name: deck_name
        description: pass the user ID
        required: true
        schema:
          type: string
  
    get:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can delete
        a deck in the system
        
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
    
    delete:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can delete
        a deck in the system
        
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
    
    put:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can delete
        a deck in the system
        
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                deck_no:
                  type: string
                last_reviewed:
                  type: string
        description: order placed for purchasing the pet
        required: true
    
    post:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can delete
        a deck in the system
        
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                card_no:
                  type: string
                difficulty:
                  type: integer
        description: order placed for purchasing the pet
        required: true
      
      
  /api/user/{user_id}/deck/{deck_name}/card/{card_no}:
    parameters:
      - in: path
        name: user_id
        description: pass the user ID
        required: true
        schema:
          type: string
      - in: path
        name: deck_name
        description: pass the user ID
        required: true
        schema:
          type: string
      - in: path
        name: card_no
        description: pass the user ID
        required: true
        schema:
          type: integer
  
    get:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can delete
        a deck in the system
        
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
    
    delete:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can delete
        a deck in the system
        
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
    
    put:
      tags:
        - developers
      description: |
        By passing in the appropriate options, you can delete
        a deck in the system
        
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                card_no:
                  type: string
                difficulty:
                  type: integer
        description: order placed for purchasing the pet
        required: true