openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - url: http://127.0.0.1:8080/
info:
  description: Flash Card API
  version: "1.0.0"
  title: Flash Card API
  contact:
    email: duttajyotisubhra@gmail.com
tags:
  - name: developers
    description: Secured Admin-only calls
  - name: users
    description: Operations available to regular users
paths:
  /api/deck/{deck_name}:
    parameters:
      - in: path
        name: deck_name
        description: pass the deck name
        required: true
        schema:
          type: string
    get:
      tags:
        - developers
      summary: returns info about a deck
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found

    delete:
      tags:
        - developers
      summary: deletes a deck
      description: |
        By passing in the appropriate options, you can delete
        a deck in the system
        
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
  /api/deck:
    post:
      tags:
        - developers
      summary: returns info about a deck
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      responses:
        '200':
          description: search results matching criteria
          
        '400':
          description: bad input parameter
          
        '404':
          description: Deck not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                deck_name:
                  type: string
                number_of_cards:
                  type: integer
                  format: int64
        description: order placed for purchasing the pet
        required: true


